server:
  port: ${PORT}

spring:
  application:
    name: SPosService
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      open-in-view: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

banka:
  servis:
    url: http://localhost:7079/api/banka/odeme

swagger:
  info:
    title: ${SWAGGER_TITLE}
    version: ${SWAGGER_VERSION}
    description: ${SWAGGER_DSC}
    termsOfService: ${SWAGGER_TOS}
    contact:
      name: ${SWAGGER_NAME}
      email: ${SWAGGER_EMAIL}